import json
from urllib.parse import urlencode



class Queries(object):

    @staticmethod
    def read_user_id():
        return json.dumps({"operationName":"ReadUserId","variables":{},"query":"query ReadUserId {\n  readUser {\n    ... on UserErrorResponse {\n      errorMessages\n      __typename\n    }\n    ... on User {\n      id\n      __typename\n    }\n    __typename\n  }\n}\n"})
    
    @staticmethod
    def read_user_portfolios():
        return json.dumps({"operationName":"MyActiveGames","variables":{},"query":"query MyActiveGames {\n  readUserPortfolios(input: {filter: ACTIVE}) {\n    ... on UserDoesNotExistError {\n      errorMessages\n      __typename\n    }\n    ... on UserPortfoliosError {\n      errorMessages\n      __typename\n    }\n    ... on PagedPortfolioList {\n      list {\n        id\n        game {\n          id\n          gameDetails {\n            ... on GameDetails {\n              active\n              description\n              endDate\n              gameType\n              id\n              name\n              numberOfPlayers\n              ownerId\n              rules {\n                allowLateEntry\n                allowMargin\n                allowOptionTrading\n                allowPortfolioResetting\n                allowPortfolioViewing\n                allowShortSelling\n                cashInterestPercent\n                commissionDollars\n                commissionPerContractDollars\n                dailyVolumePercent\n                diversificationOptionsPercent\n                diversificationPercent\n                marginInterestPercent\n                marketDelayMinutes\n                minStockForMarginDollars\n                minimumPriceDollars\n                minimumPriceToShortDollars\n                quickSellDurationMinutes\n                startingCashDollars\n                __typename\n              }\n              startDate\n              owner {\n                ... on UserResponse {\n                  id\n                  __typename\n                }\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"})
    
    @staticmethod
    def portfolio_summary_query(portfolio_id):
        return json.dumps({"operationName":"PortfolioSummary","variables":{"portfolioId":portfolio_id},"query":"query PortfolioSummary($portfolioId: String!) {\n  readPortfolio(portfolioId: $portfolioId) {\n    ... on Portfolio {\n      summary {\n        accountValue\n        annualReturn\n        buyingPower\n        cash\n        dayGainDollar\n        dayGainPercent\n        __typename\n      }\n      __typename\n    }\n    ... on PortfolioErrorResponse {\n      errorMessages\n      __typename\n    }\n    __typename\n  }\n}\n"})

    @staticmethod
    def open_stock_trades(portfolio_id):
        return json.dumps({"operationName":"PendingStockTrades","variables":{"portfolioId":portfolio_id,"holdingType":"STOCKS"},"query":"query PendingStockTrades($portfolioId: String!, $holdingType: HoldingType!) {\n  readPortfolio(portfolioId: $portfolioId) {\n    ... on PortfolioErrorResponse {\n      errorMessages\n      __typename\n    }\n    ... on Portfolio {\n      holdings(type: $holdingType) {\n        ... on CategorizedStockHoldings {\n          pendingTrades {\n            stock {\n              ... on Stock {\n                description\n                technical {\n                  lastPrice\n                  __typename\n                }\n                __typename\n              }\n              __typename\n            }\n            symbol\n            transactionTypeDescription\n            orderPriceDescription\n            tradeId\n            action\n            cancelDate\n            quantity\n            quantityType\n            transactionType\n            limit {\n              limit\n              stop\n              trailingStop {\n                percentage\n                price\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        ... on HoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedHoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"})
    
    @staticmethod
    def open_option_trades(portfolio_id):
        return json.dumps({"operationName":"PendingOptionTrades","variables":{"portfolioId":portfolio_id,"holdingType":"OPTIONS"},"query":"query PendingOptionTrades($portfolioId: String!) {\n  readPortfolio(portfolioId: $portfolioId) {\n    ... on PortfolioErrorResponse {\n      errorMessages\n      __typename\n    }\n    ... on Portfolio {\n      holdings(type: OPTIONS) {\n        ... on HoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedHoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedOptionHoldings {\n          pendingTrades {\n            option {\n              ... on Option {\n                isPut\n                expirationDate\n                lastPrice\n                strikePrice\n                stock {\n                  ... on Stock {\n                    symbol\n                    technical {\n                      lastPrice\n                      __typename\n                    }\n                    __typename\n                  }\n                  __typename\n                }\n                __typename\n              }\n              __typename\n            }\n            symbol\n            transactionTypeDescription\n            orderPriceDescription\n            tradeId\n            action\n            cancelDate\n            quantity\n            quantityType\n            transactionType\n            limit {\n              limit\n              stop\n              trailingStop {\n                percentage\n                price\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"})
    
    @staticmethod
    def open_short_trades(portfolio_id):
        return json.dumps({"operationName":"PendingStockTrades","variables":{"portfolioId":portfolio_id,"holdingType":"SHORTS"},"query":"query PendingStockTrades($portfolioId: String!, $holdingType: HoldingType!) {\n  readPortfolio(portfolioId: $portfolioId) {\n    ... on PortfolioErrorResponse {\n      errorMessages\n      __typename\n    }\n    ... on Portfolio {\n      holdings(type: $holdingType) {\n        ... on CategorizedStockHoldings {\n          pendingTrades {\n            stock {\n              ... on Stock {\n                description\n                technical {\n                  lastPrice\n                  __typename\n                }\n                __typename\n              }\n              __typename\n            }\n            symbol\n            transactionTypeDescription\n            orderPriceDescription\n            tradeId\n            action\n            cancelDate\n            quantity\n            quantityType\n            transactionType\n            limit {\n              limit\n              stop\n              trailingStop {\n                percentage\n                price\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        ... on HoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedHoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"})
    
    @staticmethod
    def cancel_order(order_id):
        return json.dumps({"operationName":"CancelTrade","variables":{"input":order_id},"query":"mutation CancelTrade($input: String!) {\n  submitCancelTrade(tradeId: $input) {\n    ... on CancelTradeErrorResponse {\n      errorMessages\n      __typename\n    }\n    __typename\n  }\n}\n"})
                          
    @staticmethod
    def refresh_token(refresh_token):
        return urlencode({'grant_type': 'refresh_token', 'refresh_token': refresh_token, 'client_id': 'finance-simulator'})

    @staticmethod
    def stock_holdings(portfolio_id):
        return json.dumps({"operationName":"StockHoldings","variables":{"portfolioId":portfolio_id,"holdingType":"STOCKS"},"query":"query StockHoldings($portfolioId: String!, $holdingType: HoldingType!) {\n  readPortfolio(portfolioId: $portfolioId) {\n    ... on PortfolioErrorResponse {\n      errorMessages\n      __typename\n    }\n    ... on Portfolio {\n      holdings(type: $holdingType) {\n        ... on HoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedHoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedStockHoldings {\n          holdingsSummary {\n            marketValue\n            dayGainDollar\n            dayGainPercent\n            totalGainDollar\n            totalGainPercent\n            __typename\n          }\n          executedTrades {\n            stock {\n              ... on Stock {\n                symbol\n                description\n                technical {\n                  lastPrice\n                  __typename\n                }\n                __typename\n              }\n              __typename\n            }\n            symbol\n            quantity\n            purchasePrice\n            marketValue\n            dayGainDollar\n            dayGainPercent\n            totalGainDollar\n            totalGainPercent\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"})
    
    @staticmethod
    def option_holdings(portfolio_id):
        return json.dumps({"operationName":"OptionHoldings","variables":{"portfolioId":portfolio_id,"holdingType":"OPTIONS"},"query":"query OptionHoldings($portfolioId: String!) {\n  readPortfolio(portfolioId: $portfolioId) {\n    ... on PortfolioErrorResponse {\n      errorMessages\n      __typename\n    }\n    ... on Portfolio {\n      holdings(type: OPTIONS) {\n        ... on HoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedHoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedOptionHoldings {\n          holdingsSummary {\n            marketValue\n            dayGainDollar\n            dayGainPercent\n            totalGainDollar\n            totalGainPercent\n            __typename\n          }\n          executedTrades {\n            option {\n              ... on SymbolNotFoundResponse {\n                errorMessages\n                __typename\n              }\n              ... on InvalidSymbolResponse {\n                errorMessages\n                __typename\n              }\n              ... on Option {\n                symbol\n                isPut\n                lastPrice\n                expirationDate\n                strikePrice\n                stock {\n                  ... on Stock {\n                    symbol\n                    description\n                    technical {\n                      lastPrice\n                      __typename\n                    }\n                    __typename\n                  }\n                  __typename\n                }\n                __typename\n              }\n              __typename\n            }\n            quantity\n            purchasePrice\n            marketValue\n            dayGainDollar\n            dayGainPercent\n            totalGainDollar\n            totalGainPercent\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"})
    
    @staticmethod
    def short_holdings(portfolio_id):
        return json.dumps({"operationName":"StockHoldings","variables":{"portfolioId":"10042674","holdingType":"SHORTS"},"query":"query StockHoldings($portfolioId: String!, $holdingType: HoldingType!) {\n  readPortfolio(portfolioId: $portfolioId) {\n    ... on PortfolioErrorResponse {\n      errorMessages\n      __typename\n    }\n    ... on Portfolio {\n      holdings(type: $holdingType) {\n        ... on HoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedHoldingsErrorResponse {\n          errorMessages\n          __typename\n        }\n        ... on CategorizedStockHoldings {\n          holdingsSummary {\n            marketValue\n            dayGainDollar\n            dayGainPercent\n            totalGainDollar\n            totalGainPercent\n            __typename\n          }\n          executedTrades {\n            stock {\n              ... on Stock {\n                symbol\n                description\n                technical {\n                  lastPrice\n                  __typename\n                }\n                __typename\n              }\n              __typename\n            }\n            symbol\n            quantity\n            purchasePrice\n            marketValue\n            dayGainDollar\n            dayGainPercent\n            totalGainDollar\n            totalGainPercent\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"})